language: python
python:
    - 3.5.2
deploy:
    provider: heroku
    buildpack: python
    api_key:
        secure: $ENV_HEROKU_API_KEY 
    strategy: git
    app: examino 
    run:
        - "ls ./"
        - "python examino/manage.py syncdb --noinput --settings=settings.heroku"
        - "python examino/manage.py migrate --all --settings=settings.heroku"
        - restart
install:
      - pip install -r requirments.txt
script: "coverage run --source=. ./examino/manage.py test -v 2"
