language: python
deploy:
	provider: heroku
	buildpack: python
	api_key:
		secure: $ENV_HEROKU_API_KEY 
	strategy: git
	app: examino 
	run:
		- "python examino/manage.py syncdb --noinput --settings=settings.heroku"
		- "python examino/manage.py migrate --all --settings=settings.heroku"
		- restart
script: "coverage run --source=. examino/manage.py test -v 2"
